### ISSUE TITLE
本仓库一个或多个文件涉嫌非法复制

### ISSUE THREAD

**Issue by MrZhang365** [NIHAOAWA/NIHAOplay#2]
请注意，本仓库的一个或多个文件涉嫌非法复制（未遵守许可证要求），请及时处理，否则后果自负。

受影响的文件：
README.md

被非法复制的文件：
https://github.com/MrZhang365/ZhangBlog/blob/main/README.md

被非法复制的文件许可证：
Apache-2.0

详细内容：
> 感谢您对NIHAOplay的支持，我们将会继续更新，为您带来更好的体验。

> 感谢您对ZhangBlog的大力支持，我们将会稳步更新，为您提供最好的体验。

***
> 该项目大致完工，后期将会继续更新更多功能。

> 项目基本完工，未来将添加更多的功能

***
> 本项目许可证为 Apache-2.0，如果您要使用或改编，请在首页明确标注“本网站基于NIHAOplay”，注意要注明本仓库的链接

> 本项目许可证为 Apache-2.0，如果您要使用或改编，请在首页明确标注“本网站基于[小张博客](https://githubfast.com/MrZhang365/ZhangBlog)”，注意要注明本仓库的链接

**Comment by NIHAOAWA** [comment]
我改一下哈

**Comment by NIHAOAWA** [comment]
我已经改完了

**Comment by MrZhang365** [comment]
详细信息 第一个 没有改

**Comment by NIHAOAWA** [comment]
> 详细信息 第一个 没有改

您稍等 现在改

**Comment by MrZhang365** [comment]
还有，我要求你公开为你所有非法复制的行为道歉

**Comment by NIHAOAWA** [comment]
> 还有，我要求你公开为你所有非法复制的行为道歉

嗯 我并不应该非法复制他人内容而构成抄袭
当时我写文档时只是为了“快”，
却没有想到这个“快”所带来的后果。
这件事确实是我错了，对不起。
以后我再写文档时会自己写，
不会继续非法复制，你可以进行监督

**Comment by zhiziqixingdeng** [comment]
@NIHAOAWA 你确实该道歉

**Comment by zhiziqixingdeng** [comment]
@NIHAOAWA 你还非法复制过我的东西呢
